### PR TITLE
Level Design PR

### PR DESCRIPTION
**Pull request by Guicha**
- Changed the obstacles sprites
- Fixed an obstacle bug that made the game crash
- Added different enemy movement
- Separation distance adjusted

We are still working on the different backgrounds, and we will be pushing less saturated background in our next PR as said in our meeting!

### CODE REVIEW

**Comment by DongWonLee2** [comment]
Is it possible to solve issue #89 with this PR?

**Comment by Guicha** [comment]
Yes we addressed this issue in this PR ! It should be fine right now

**Comment by aeioiie** [comment]
I'm a member of Nice-HUD team.
I have checked this PR, and I have confirmed that it works well. However, there was a little bit of confusion playing the game because the color of the stone was similar to the coin's color. How about changing the color of the stone to another color, like gray or something? I think it would be a better gameplay!

**Comment by Guicha** [comment]
That's a nice suggestion here I'll discuss about it in my team :)

**Comment by aeioiie** [comment]
Thanks!

**Comment by Guicha** [comment]
We changed the color from ORANGE to light grey it should be up in our next PR !

**Pull request merged**
